version: "3"
volumes:
  postgres:
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: bookist
      POSTGRES_PASSWORD: bookist
      POSTFRES_DB: bookist
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'